backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Titulo", name: "title", widget: "markdown" }
      - { label: "Descrição", name: "description", widget: "markdown" }
      - { label: "Data de públicação", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", default: "/img/default-thumb.png" }

      - label: "Type"
        name: "type"
        widget: "select"
        options: ["portugal", "italia"]

      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - { label: "Tag Name", name: "tag", widget: "string" }

      - label: "Content"
        name: "content"
        widget: "object"
        fields:
          - { label: "Titulo", name: "title", widget: "markdown" }
          - { label: "Paragrafo", name: "paragraph", widget: "markdown" }
          - { label: "Imagem", name: "imagem", widget: "image" }

