backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: img

collections:
  - label: "Post"
    name: "Post"
    folder: "content/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Titulo", name: "title", widget: "markdown" }
      - { label: "Descrição", name: "description", widget: "markdown" }
      - { label: "Data de públicação", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", default: "/img/default-thumb.png" }

      - label: "Tipo"
        name: "type"
        widget: "select"
        options: ["portugal", "italia"]

      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - { label: "name", name: "name", widget: "string" }

      - { label: "Conteúdo", name: "content", widget: "markdown" }
