backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Titulo", name: "title", widget: "markdown" }
      - { label: "Data de públicação", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
